server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://manish:fBxLDjziEgA6CCEn@vrv.tzoxj.mongodb.net/?retryWrites=true&w=majority&appName=vrv
      database: user



logging:
  level:
    root: WARN

otp:
  expire:
    time: 600

